username: "user@gmail.com"
password: "pa$$word"
accountId: "abcdefgh-abcd-1234-1234-abcdefghijk"
apprise:
  - url: "mailto://user:password@gmail.com"
  - url: "whatsapp://AccessToken@FromPhoneID/ToPhoneNo"
